# Generated by Django 6.0.5 on 2026-05-13 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('edad', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='candidatas/')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_candidatas/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('candidata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='candidatas.candidata')),
            ],
        ),
    ]
