# Generated by Django 4.2 on 2026-05-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidata',
            name='curso',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidata',
            name='division',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidata',
            name='especialidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidata',
            name='estatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='candidata',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidata',
            name='pasatiempos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidata',
            name='proyectos_aspiraciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidata',
            name='turno',
            field=models.CharField(blank=True, choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
