# Generated by Django 4.2 on 2026-05-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidatas', '0002_candidata_curso_candidata_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belleza', models.IntegerField(default=0)),
                ('simpatia', models.IntegerField(default=0)),
                ('elegancia', models.IntegerField(default=0)),
                ('vestimenta', models.IntegerField(default=0)),
                ('maquillaje', models.IntegerField(default=0)),
                ('hinchada', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='candidatas.candidata')),
            ],
            options={
                'verbose_name_plural': 'Puntuaciones',
            },
        ),
    ]
