# Generated by Django 4.2 on 2026-05-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatas', '0003_puntuacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='candidata',
            new_name='candidatura',
        ),
        migrations.RenameField(
            model_name='puntuacion',
            old_name='candidata',
            new_name='candidatura',
        ),
        migrations.AlterField(
            model_name='candidata',
            name='turno',
            field=models.CharField(blank=True, choices=[('manana', 'Manana'), ('tarde', 'Tarde'), ('noche', 'Noche')], default='', max_length=10),
        ),
    ]
