# Generated by Django 4.2 on 2026-05-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatas', '0004_rename_candidata_foto_candidatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidata',
            name='numero',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de candidatura', null=True),
        ),
    ]
